# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(FFFFFB)
$foreground = rgb(212628)
$color0 = rgb(FFFFFB)
$color1 = rgb(838476)
$color2 = rgb(546E6F)
$color3 = rgb(636864)
$color4 = rgb(A43231)
$color5 = rgb(3D4547)
$color6 = rgb(373F43)
$color7 = rgb(212628)
$color8 = rgb(929384)
$color9 = rgb(AFB19D)
$color10 = rgb(709294)
$color11 = rgb(848B85)
$color12 = rgb(DB4341)
$color13 = rgb(525C5F)
$color14 = rgb(495459)
$color15 = rgb(0B0D0D)
